# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import service_pb2 as service__pb2
except ImportError:
    import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SigningOracleStub:
    """Signing Oracle Service for CyberCore
    Provides secure signing for agents without exposing private keys

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sign = channel.unary_unary(
                '/cybercore.oracle.v1.SigningOracle/Sign',
                request_serializer=service__pb2.SignRequest.SerializeToString,
                response_deserializer=service__pb2.SignResponse.FromString,
                _registered_method=True)
        self.GetPublicKey = channel.unary_unary(
                '/cybercore.oracle.v1.SigningOracle/GetPublicKey',
                request_serializer=service__pb2.PublicKeyRequest.SerializeToString,
                response_deserializer=service__pb2.PublicKeyResponse.FromString,
                _registered_method=True)
        self.DeriveAddress = channel.unary_unary(
                '/cybercore.oracle.v1.SigningOracle/DeriveAddress',
                request_serializer=service__pb2.AddressRequest.SerializeToString,
                response_deserializer=service__pb2.AddressResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/cybercore.oracle.v1.SigningOracle/Health',
                request_serializer=service__pb2.HealthRequest.SerializeToString,
                response_deserializer=service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListChains = channel.unary_unary(
                '/cybercore.oracle.v1.SigningOracle/ListChains',
                request_serializer=service__pb2.ListChainsRequest.SerializeToString,
                response_deserializer=service__pb2.ListChainsResponse.FromString,
                _registered_method=True)


class SigningOracleServicer:
    """Signing Oracle Service for CyberCore
    Provides secure signing for agents without exposing private keys

    """

    def Sign(self, request, context):
        """Sign a message with a derived key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicKey(self, request, context):
        """Get public key info for a derivation path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeriveAddress(self, request, context):
        """Derive address for a path
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChains(self, request, context):
        """Get supported chains
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SigningOracleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=service__pb2.SignRequest.FromString,
                    response_serializer=service__pb2.SignResponse.SerializeToString,
            ),
            'GetPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKey,
                    request_deserializer=service__pb2.PublicKeyRequest.FromString,
                    response_serializer=service__pb2.PublicKeyResponse.SerializeToString,
            ),
            'DeriveAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.DeriveAddress,
                    request_deserializer=service__pb2.AddressRequest.FromString,
                    response_serializer=service__pb2.AddressResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=service__pb2.HealthRequest.FromString,
                    response_serializer=service__pb2.HealthResponse.SerializeToString,
            ),
            'ListChains': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChains,
                    request_deserializer=service__pb2.ListChainsRequest.FromString,
                    response_serializer=service__pb2.ListChainsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cybercore.oracle.v1.SigningOracle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cybercore.oracle.v1.SigningOracle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SigningOracle:
    """Signing Oracle Service for CyberCore
    Provides secure signing for agents without exposing private keys

    """

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybercore.oracle.v1.SigningOracle/Sign',
            service__pb2.SignRequest.SerializeToString,
            service__pb2.SignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybercore.oracle.v1.SigningOracle/GetPublicKey',
            service__pb2.PublicKeyRequest.SerializeToString,
            service__pb2.PublicKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeriveAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybercore.oracle.v1.SigningOracle/DeriveAddress',
            service__pb2.AddressRequest.SerializeToString,
            service__pb2.AddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybercore.oracle.v1.SigningOracle/Health',
            service__pb2.HealthRequest.SerializeToString,
            service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cybercore.oracle.v1.SigningOracle/ListChains',
            service__pb2.ListChainsRequest.SerializeToString,
            service__pb2.ListChainsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
